### ISSUE TITLE
Add : Yahoo COVID-19 dataset.

### ISSUE THREAD

**Issue by peterirani** [sfu-db/covid19-datasets#24]
The dataset can be found here:
https://github.com/yahoo/covid-19-data

Please perform the following tasks for this dataset:
1) Create a dataset-details page and fill in all the relevant info.
2) Generate pandas-profile webpage and add the link to the webpage as described in [how to contribute](https://github.com/sfu-db/covid19-datasets/blob/master/assets/how-to-contribute-COVID19repo.md) page. 
3) Add your .py script that was used to generate the pandas-profile report to `scripts` directory. 
4) After adding all the files. Please comment on this issue with the link which is to be added to README.md. For example the typical link would look like this ` * ![OK_ICON](https://github.com/sfu-db/covid19-datasets/blob/master/assets/ok_icon.png)[**Name_of_your_dataset**](/datasets-details/**name_of_your_dataset.md**)`. Please do NOT add this to README.md by yourself, the page owners/collaborators will add them. 

**PMP RAs** - Please feel to assign this to yourself by commenting on it and I will assign this to you. Also please don't forget to `fetch` and `rebase` the `upstream` before working on/ submitting your PR.

**Comment by kla55** [comment]
Hey Peter, 

I will take this one

**Comment by kla55** [comment]
I guess someone did this one already

**Comment by kla55** [comment]
same dataset - https://github.com/sfu-db/covid19-datasets/blob/master/datasets-details/radiography-kaggle-COVID-19-dataset.md

**Comment by peterirani** [comment]
Hi Ken, the link was incorrect. I have added the correct link in the description now. Do you want to work on this dataset?

**Comment by kla55** [comment]
let me continue to work on this

**Comment by peterirani** [comment]
Completed by Ken (Kla55)
